modLoader="javafml"
loaderVersion="[47,)"

license="Apache License 2.0"
issueTrackerURL="https://createfreundesmp.github.io"
showAsResourcePack=false

[[mods]]
modId="cfsmp"
version="2.0.1"
displayName="Create: FreundeSMP Core"
updateJSONURL="https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
displayURL="https://createfreundesmp.github.io"
logoFile="cfsmp.png"
credits="DoktorCraft23 (Coder), Mete74_ay (Artist)"
authors="Author"
description='''
  The Coremod powering the Create: FreundeSMP
  '''
displayTest="MATCH_VERSION"

[[dependencies.cfsmp]]
modId="forge"
mandatory=true
versionRange="[47.4.0]"
ordering="NONE"
side="BOTH"

[[dependencies.cfsmp]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"